from __future__ import annotations

BLOCK_PERSIST_DEFS = {
    'DOWNLOAD': {'name': 'Download Highest Quality', 'description': 'Download new output image, pick highest quality src', 'icon': 'download', 'default_enabled': True, 'default_selector': '', 'default_color': '#00FFAA', 'default_timeout_ms': 30000, 'required': True, 'category': 'action', 'labels': {'timeout_ms': 'Download timeout (ms)'}},
    'VALIDATE': {'name': 'Validate Image', 'description': 'Validate downloaded bytes is valid image, not HTML, dimensions >0 via PIL', 'icon': 'verified', 'default_enabled': True, 'default_selector': '', 'default_color': '#00FFAA', 'default_timeout_ms': 5000, 'required': True, 'category': 'verify'},
    'SAVE': {'name': 'Save *_AI.ext Atomically', 'description': 'Save beside source with _AI suffix, unique if exists, atomic write', 'icon': 'save', 'default_enabled': True, 'default_selector': '', 'default_color': '#4ADE80', 'default_timeout_ms': 5000, 'required': True, 'category': 'persist', 'extra_defaults': {'suffix': '_AI', 'overwrite': False}, 'labels': {'suffix': 'Suffix (e.g. _AI)', 'overwrite': 'Overwrite if exists'}},
    'ADVANCE': {'name': 'Advance & Persist', 'description': 'Mark job completed, recalculate progress, persist state atomically', 'icon': 'check_circle', 'default_enabled': True, 'default_selector': '', 'default_color': '#4ADE80', 'default_timeout_ms': 2000, 'required': True, 'category': 'persist'},
    'SAVE_DESCRIPTION_JSON': {'name': 'Save Description JSON', 'description': 'Save text description as JSON file with same name as source image (icon.png -> icon.json) in same dir. For Generate Image Description workflow.', 'icon': 'save', 'default_enabled': True, 'default_selector': '', 'default_color': '#4ADE80', 'default_timeout_ms': 5000, 'required': False, 'category': 'persist', 'extra_defaults': {'overwrite': False, 'include_prompt': True, 'include_job_id': True}, 'labels': {'overwrite': 'Overwrite if exists', 'include_prompt': 'Include prompt in JSON', 'include_job_id': 'Include job_id in JSON'}},
}
