from __future__ import annotations

DEFAULT_STACK_ORDER = ['HIGHLIGHT_ATTACH', 'OBSERVE_BASELINE', 'CHECK_SECURITY', 'AWAIT_PROCESSING_IMAGE', 'ATTACH_IMAGE', 'VERIFY_ATTACHMENT', 'HIGHLIGHT_PROMPT', 'INSERT_PROMPT', 'VERIFY_PROMPT', 'HIGHLIGHT_SUBMIT', 'SUBMIT', 'WAIT_OUTPUT', 'DOWNLOAD', 'VALIDATE', 'SAVE', 'ADVANCE']

DESCRIPTION_STACK_ORDER = ['HIGHLIGHT_ATTACH', 'OBSERVE_TEXT_BASELINE', 'CHECK_SECURITY', 'AWAIT_PROCESSING_IMAGE', 'ATTACH_IMAGE', 'VERIFY_ATTACHMENT', 'HIGHLIGHT_PROMPT', 'INSERT_PROMPT', 'VERIFY_PROMPT', 'HIGHLIGHT_SUBMIT', 'SUBMIT', 'WAIT_TEXT_OUTPUT', 'SAVE_DESCRIPTION_JSON', 'ADVANCE']
