"""stores/history_models — fingerprint & value-object contracts.

Design refs: docs/archive/2026-09-09-test-suite/BACKEND_TESTS_DESIGN_2026-09-09.md §HM#1–5.

The docstring's hard promise: the fingerprint is computed in TWO places
(backend/js/chat_agent.js over charCodeAt = UTF-16 code units, and here)
and "both implementations are pinned by tests to the same constants".
The constants below were generated by executing the REAL JavaScript
implementation (node, backend/js/chat_agent.js) — if Python ever drifts
from JS, the archive starts splitting one conversation into two.

Also proven: occ sensitivity, dedupe_key ignoring occ, from_dict on
agent garbage, round-trip losslessness, JSON-safe result objects.

Run with:  python3 tests/unit/backend/test_history_models.py
"""

import json
import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))))))

from stores.history_models import (  # noqa: E402
    LineIdentity,
    MAX_LIVE_ITEMS,
    Alignment,
    AppendResult,
    MessageRecord,
    SyncResult,
    dedupe_key,
    fingerprint,
)

#: generated with: node (backend/js/chat_agent.js fingerprint())
JS_PINNED = {
    ("in", "Nick", "17:31", "text", "hello world", 0):
        "6c9ff17126656bda",
    ("in", "Nick", "17:31", "text", "hello world", 1):
        "6b9fefde0262f497",
    ("out", "Me", "00:05", "gif", "https://x/y.gif", 0):
        "100f0f580b320a89",
    # astral-plane emoji: UTF-16 surrogate pair — charCodeAt semantics
    ("in", "Анна", "23:59", "text", "привет 😀 мир", 2):
        "43cec1c2abb473d7",
    # U+2028 LINE SEPARATOR — a "newline" JS must hash, not break on
    ("in", "Nick", "17:31", "text", "a b", 0):
        "2b5f310848b7ab31",
}


class TestFingerprint(unittest.TestCase):

    def test_python_matches_the_javascript_constants(self):
        for args, expected in JS_PINNED.items():
            self.assertEqual(fingerprint(LineIdentity(*args[:-1]), args[-1]),
                             expected,
                             f"JS/Python fingerprint drift at {args!r}")

    def test_stable_and_occurrence_sensitive(self):
        a = fingerprint(LineIdentity("in", "N", "17:31", "text", "x"), 0)
        self.assertEqual(a, fingerprint(LineIdentity("in", "N", "17:31", "text", "x"), 0))
        self.assertNotEqual(a, fingerprint(LineIdentity("in", "N", "17:31", "text", "x"), 1))
        self.assertNotEqual(a, fingerprint(LineIdentity("out", "N", "17:31", "text", "x"), 0))
        self.assertNotEqual(a, fingerprint(LineIdentity("in", "N", "17:32", "text", "x"), 0))

    def test_astral_emoji_counts_as_two_utf16_units(self):
        """😀 is 2 UTF-16 units; the hash must see BOTH (charCodeAt)."""
        with_emoji = fingerprint(LineIdentity("in", "N", "t", "text", "😀"), 0)
        # the same string truncated to its first surrogate unit is the
        # 'lone surrogate' JS would see mid-pair — different hash
        lone = fingerprint(LineIdentity("in", "N", "t", "text", "\ud83d"), 0)
        self.assertNotEqual(with_emoji, lone)
        # equal UTF-16 length, different units → different hash
        bmp_two = fingerprint(LineIdentity("in", "N", "t", "text", "aa"), 0)
        self.assertNotEqual(with_emoji, bmp_two)

    def test_dedupe_key_ignores_occ(self):
        self.assertEqual(
            dedupe_key(LineIdentity("in", "N", "17:31", "text", "x")),
            fingerprint(LineIdentity("in", "N", "17:31", "text", "x"), 0),
            "dedupe_key must be the occ=0 fingerprint")
        self.assertNotEqual(dedupe_key(LineIdentity("in", "N", "17:31", "text", "x")),
                            dedupe_key(LineIdentity("in", "N", "17:31", "text", "y")))
        self.assertNotEqual(dedupe_key(LineIdentity("in", "N", "17:31", "text", "x")),
                            dedupe_key(LineIdentity("out", "N", "17:31", "text", "x")))

    def test_empty_and_none_inputs_never_crash(self):
        blank = fingerprint(LineIdentity("", "", "", "", ""), 0)
        self.assertEqual(len(blank), 16)
        self.assertEqual(fingerprint(LineIdentity(None, None, None, None, None)),
                         fingerprint(LineIdentity("", "", "", "", ""), 0))


class TestMessageRecord(unittest.TestCase):

    def test_round_trip_is_lossless(self):
        rec = MessageRecord(fp="deadbeef", direction="out", from_nick="Me",
                            kind="gif", text="", media_url="https://x/y.gif",
                            media_kind="gif", ts_display="09:01", occ=3,
                            idx=7)
        clone = MessageRecord.from_dict(rec.to_dict())
        self.assertEqual(clone, rec)

    def test_from_dict_maps_the_agent_field_names(self):
        rec = MessageRecord.from_dict({
            "dir": "out", "from": "Me", "kind": "text",
            "text": "привет", "time": "10:20", "occ": 1, "idx": 2,
        })
        self.assertEqual(rec.direction, "out")
        self.assertEqual(rec.from_nick, "Me")
        self.assertEqual(rec.ts_display, "10:20")
        self.assertEqual(rec.occ, 1)
        self.assertTrue(rec.fp, "ensure_fp must run on from_dict")

    def test_from_dict_on_agent_garbage_stays_usable(self):
        for garbage in ({}, None, {"dir": 5, "from": ["x"], "occ": "z",
                                   "idx": None, "text": 12},
                        {"media": "notadict", "text": "hi"}):
            rec = MessageRecord.from_dict(garbage)   # must not raise
            self.assertIsInstance(rec, MessageRecord)
            self.assertIsInstance(rec.payload, str)

    def test_media_payload_and_dup_key(self):
        media = MessageRecord(kind="image", media_url="https://x/a.jpg",
                              ts_display="08:00")
        self.assertEqual(media.payload, "https://x/a.jpg")
        text = MessageRecord(kind="text", text="hi", ts_display="08:00")
        self.assertEqual(text.payload, "hi")
        self.assertNotEqual(media.dup_key, text.dup_key)

    def test_ensure_fp_only_computes_once(self):
        rec = MessageRecord()
        first = rec.ensure_fp()
        rec.text = "changed after fp"
        self.assertEqual(rec.ensure_fp(), first,
                         "ensure_fp must not recompute an existing fp")


class TestResultObjects(unittest.TestCase):

    def test_every_to_dict_is_json_safe(self):
        objs = [AppendResult(added=2, records=[{"a": 1}]),
                Alignment(start=3, gap=True, reason="cap"),
                SyncResult(ok=True, nick="N", chunks=[1, 2])]
        for obj in objs:
            json.dumps(obj.to_dict(), ensure_ascii=False)   # must not raise

    def test_max_live_items_is_the_documented_bound(self):
        self.assertIsInstance(MAX_LIVE_ITEMS, int)
        self.assertGreater(MAX_LIVE_ITEMS, 0)


if __name__ == "__main__":
    unittest.main(verbosity=2)
