from __future__ import annotations
from ..selector import SelectorObject
from .constants import NEW_CHAT_PATH, CONVERSATION_PATH_PREFIX

SELECTORS_ACCOUNT = {
    "account_email": SelectorObject(
        name='account_email',
        primary='[data-sidebar="menu"] div.font-heading.truncate',
        fallbacks=['[data-sidebar="menu"] button div.truncate', '[data-sidebar="footer"] div.font-heading.truncate', '[data-sidebar="footer"] button div.truncate', '[data-sidebar="rail"] div.font-heading.truncate', '[data-sidebar="menu"] button span:has(> img) + div'],
        scope='[data-sidebar="sidebar"]',
        mustBeVisible=True,
        mustBeEnabled=False,
        expectedCount=1,
        textCondition='@',
        textConditionType='contains',
        presenceSelector=None,
        verification='visible sidebar row whose short text holds the signed-in account email',
        evidence='docs/research/Directly Chat with Frontier Image Generation AI Models.html: ul[data-sidebar=menu] > button > div.font-heading.truncate = zeusthunder1991@gmail.com (avatar span sibling); the same string also sits in the RSC script payload, which is not probed. 2026-09-25 (Firefox identify): owner evidence div.font-heading.min-w-0.flex-1.truncate = mailreceiverpro@gmail.com; last fallback is structural — the text div right after the avatar span, class-free',
        lastVerified='2026-09-25',
    ),
    "new_chat_button": SelectorObject(
        name='new_chat_button',
        primary='a[href="/image/direct"]',
        fallbacks=['li[data-sidebar="menu-item"] a[href="/image/direct"]', 'a[data-sidebar="menu-button"][href="/image/direct"]'],
        scope='li[data-sidebar="menu-item"]',
        mustBeVisible=True,
        mustBeEnabled=True,
        expectedCount=1,
        textCondition='New Chat',
        textConditionType='contains',
        presenceSelector=None,
        verification='click returns to clean new chat; wait readyState complete + page ready + empty composer',
        evidence='user HTML 2026-09-16: li[data-sidebar=menu-item] > a[href=/image/direct] > span New Chat',
        lastVerified='2026-09-16',
    ),
    "assistant_message": SelectorObject(
        name='assistant_message',
        primary='div[data-message-author-role="assistant"]',
        fallbacks=['div.group.flex.w-full.flex-col:has(div.markdown)', 'div.markdown', 'div.prose', 'div[data-testid="conversation-turn"] div.markdown', 'main div.flex.flex-col.gap-3 div.markdown', 'div.no-scrollbar div.markdown', 'div.flex.w-full.flex-row.justify-start div.markdown', 'div.group:has(div.markdown) div.markdown'],
        scope=None,
        mustBeVisible=True,
        mustBeEnabled=False,
        expectedCount=0,
        textCondition=None,
        textConditionType='equals',
        presenceSelector=None,
        verification='assistant text response after user prompt, contains generated description',
        evidence='arena.ai chat: assistant messages contain markdown with text response; for description tasks, output is text not image',
        lastVerified='2026-09-28',
    ),
    "assistant_text_output": SelectorObject(
        name='assistant_text_output',
        primary='div[data-message-author-role="assistant"] div.markdown',
        fallbacks=['div.group div.markdown', 'div.markdown p', 'div.prose p', 'main div[data-message-author-role="assistant"]', 'div.no-scrollbar div[data-message-author-role="assistant"] div.markdown', 'div.flex.justify-start div.markdown'],
        scope=None,
        mustBeVisible=True,
        mustBeEnabled=False,
        expectedCount=0,
        textCondition=None,
        textConditionType='equals',
        presenceSelector=None,
        verification='text content of assistant message for description generation',
        evidence='text output detection for generate-image-description workflow',
        lastVerified='2026-09-28',
    ),
}
