from __future__ import annotations
from ..selector import SelectorObject
from .constants import NEW_CHAT_PATH, CONVERSATION_PATH_PREFIX

SELECTORS_CHAT = {
    "model_label": SelectorObject(
        name='model_label',
        primary='span.truncate',
        fallbacks=['span.font-mono.text-sm'],
        scope='div.flex.min-w-0.flex-1.items-center.gap-2',
        mustBeVisible=True,
        mustBeEnabled=False,
        expectedCount=1,
        textCondition='Max',
        textConditionType='equals',
        presenceSelector=None,
        verification='visible span.truncate with text Max indicates model row',
        evidence='Directly Chat...html + spec A',
        lastVerified='2026-09-15',
    ),
    "processing_spinner": SelectorObject(
        name='processing_spinner',
        primary='div.animate-spin',
        fallbacks=[],
        scope=None,
        mustBeVisible=True,
        mustBeEnabled=False,
        expectedCount=0,
        textCondition=None,
        textConditionType='equals',
        presenceSelector=None,
        verification='spinner visible near model label indicates processing. User provided HTML: <div class="flex min-w-0 flex-1 items-center gap-2"><div class="h-5 w-5 flex-shrink-0 animate-spin"><canvas></canvas></div><span><span class="truncate">Response A</span></span></div> — indicates generating. Wait for spinner to disappear + new output image to appear.',
        evidence='spec A + user report 2026-09-16 with Response A/B spinner',
        lastVerified='2026-09-19',
    ),
    "add_files_button": SelectorObject(
        name='add_files_button',
        primary='button[aria-label="Add files"]',
        fallbacks=['button[aria-label*="add" i][aria-label*="file" i]', 'button[aria-label*="attach" i]', 'button[aria-label*="upload" i]', 'button[title*="attach" i]'],
        scope='form:has(textarea[name="message"])',
        mustBeVisible=True,
        mustBeEnabled=True,
        expectedCount=1,
        textCondition=None,
        textConditionType='equals',
        presenceSelector=None,
        verification='click triggers file chooser or file input',
        evidence='Directly Chat...html confirmed',
        lastVerified='2026-09-15',
    ),
    "add_files_menu_item": SelectorObject(
        name='add_files_menu_item',
        primary='[role="menuitem"]:has(svg.lucide-paperclip)',
        fallbacks=['[role="menu"] :has(> svg.lucide-paperclip)', '[data-radix-popper-content-wrapper] :has(> svg.lucide-paperclip)', ':is(button, [role="menuitem"], [role="option"], label, a, div):has(> svg.lucide-paperclip):has(> span > span)'],
        scope=None,
        mustBeVisible=True,
        mustBeEnabled=True,
        expectedCount=1,
        textCondition='Add files',
        textConditionType='contains',
        presenceSelector=None,
        verification='the + (add_files_button) opens a popup; this item opens the OS file dialog',
        evidence="user HTML + screenshot 2026-09-26: item > span(span 'Add files', span 'Up to 15MB per file') + svg.lucide-paperclip",
        lastVerified='2026-09-26',
    ),
    "file_input": SelectorObject(
        name='file_input',
        primary='form input[type="file"][accept*="image"]',
        fallbacks=['input[type="file"][accept*="image"]', 'input[type="file"]'],
        scope='form',
        mustBeVisible=False,
        mustBeEnabled=True,
        expectedCount=1,
        textCondition=None,
        textConditionType='equals',
        presenceSelector='input[type="file"]',
        verification='can set files via CDP DOM.setFileInputFiles',
        evidence='Directly Chat...html confirmed hidden input; presence selector is readiness-gate broad form',
        lastVerified='2026-09-19',
    ),
    "attachment_preview_container": SelectorObject(
        name='attachment_preview_container',
        primary='div.flex.flex-wrap.gap-2',
        fallbacks=[],
        scope='form',
        mustBeVisible=True,
        mustBeEnabled=False,
        expectedCount=1,
        textCondition=None,
        textConditionType='equals',
        presenceSelector=None,
        verification='container exists above textarea',
        evidence='spec C',
        lastVerified='2026-09-15',
    ),
    "attachment_preview_image": SelectorObject(
        name='attachment_preview_image',
        primary='div.flex.flex-wrap.gap-2 img[alt]',
        fallbacks=['div.flex.flex-wrap.gap-2 img[src^="blob:"]', 'form img[src^="blob:"]'],
        scope='form',
        mustBeVisible=True,
        mustBeEnabled=False,
        expectedCount=1,
        textCondition=None,
        textConditionType='equals',
        presenceSelector=None,
        verification='preview is new, visible, inside active input area and matches expected filename when available',
        evidence='spec C; list matches live JS_VERIFY_ATTACHMENT probe (cdp_arena.py)',
        lastVerified='2026-09-19',
    ),
    "remove_file_button": SelectorObject(
        name='remove_file_button',
        primary='button[aria-label="Remove file"]',
        fallbacks=['div.flex.flex-wrap.gap-2 button[aria-label="Remove file"]', 'button[type="button"][aria-label="Remove file"]'],
        scope='div.flex.flex-wrap.gap-2',
        mustBeVisible=True,
        mustBeEnabled=True,
        expectedCount=1,
        textCondition=None,
        textConditionType='equals',
        presenceSelector=None,
        verification='click removes preview',
        evidence='spec D',
        lastVerified='2026-09-15',
    ),
}
