from __future__ import annotations
from ..selector import SelectorObject
from .constants import NEW_CHAT_PATH, CONVERSATION_PATH_PREFIX

SELECTORS_COMPOSER = {
    "prompt_textarea": SelectorObject(
        name='prompt_textarea',
        primary='textarea[name="message"]',
        fallbacks=['textarea[placeholder^="Describe"]', 'textarea[rows="1"]'],
        scope='form',
        mustBeVisible=True,
        mustBeEnabled=True,
        expectedCount=1,
        textCondition=None,
        textConditionType='equals',
        presenceSelector=None,
        verification='after insertion, textarea.value equals expected prompt exactly',
        evidence='Directly Chat...html confirmed; list matches live JS_INSERT_PROMPT probe (cdp_arena.py)',
        lastVerified='2026-09-19',
    ),
    "send_button": SelectorObject(
        name='send_button',
        primary='button[aria-label="Send message"]:not([disabled])',
        fallbacks=['form button[aria-label="Send message"]', 'button[aria-label="Send message"]'],
        scope='form',
        mustBeVisible=True,
        mustBeEnabled=True,
        expectedCount=1,
        textCondition=None,
        textConditionType='equals',
        presenceSelector='button[aria-label="Send message"]',
        verification='click once, confirm processing/loading state, prevent duplicate. State scans use presenceSelector so disabled buttons are still found (JS_SEND_STATE, readiness gate).',
        evidence='Directly Chat...html confirmed disabled has opacity-50 pointer-events-none; list matches live JS_CLICK_SEND probe (cdp_arena.py)',
        lastVerified='2026-09-19',
    ),
    "output_region": SelectorObject(
        name='output_region',
        primary='div.no-scrollbar.relative.flex.w-full.flex-1.flex-col.overflow-x-auto',
        fallbacks=['div.no-scrollbar', 'main div.flex.flex-col.gap-3'],
        scope=None,
        mustBeVisible=True,
        mustBeEnabled=False,
        expectedCount=1,
        textCondition=None,
        textConditionType='equals',
        presenceSelector='div.no-scrollbar',
        verification='output observation container exists; readiness gate probes the broad form',
        evidence='spec G',
        lastVerified='2026-09-19',
    ),
    "user_message": SelectorObject(
        name='user_message',
        primary='div.group.flex-col.self-end',
        fallbacks=['div.justify-end > div.group.self-end'],
        scope='ol',
        mustBeVisible=False,
        mustBeEnabled=False,
        expectedCount=0,
        textCondition=None,
        textConditionType='equals',
        presenceSelector=None,
        verification="an image inside the user's own message is the uploaded reference, never an output (I-70)",
        evidence='saved page: div.mx-auto.max-w-[800px].flex.w-full.justify-end > div.group.flex.flex-col.gap-1.self-end > … > img.aspect-square.w-32.cursor-pointer',
        lastVerified='2026-09-27',
    ),
    "output_image": SelectorObject(
        name='output_image',
        primary='div.no-scrollbar img[src*=".r2.cloudflarestorage.com/"]',
        fallbacks=['div.no-scrollbar img[src*="messages-prod."]', 'div.no-scrollbar img[loading="lazy"].aspect-square', 'img.aspect-square.cursor-pointer', 'img.cursor-pointer', 'div.flex img[src*=".r2.cloudflarestorage.com/"]', 'main img[src*=".r2.cloudflarestorage.com/"]', 'div.no-scrollbar img[src^="https://"]', 'img.aspect-square.w-full', 'img[src*=".r2.cloudflarestorage.com/"]', 'img[src*="messages-prod"]', 'img.h-\\[50vh\\]', 'img.w-\\[50vh\\]', 'ol img[src^="https://"]', 'main img'],
        scope=None,
        mustBeVisible=True,
        mustBeEnabled=False,
        expectedCount=0,
        textCondition=None,
        textConditionType='equals',
        presenceSelector=None,
        verification='capture all matching nodes and src before submission, result must be newly inserted or new source after submission, appear after current prompt, finish loading, nonzero natural dimensions. Wait for processing spinner to disappear first.',
        evidence='spec G + user report 2026-09-16; list matches live output_probes v4 SELECTORS_V3 exactly',
        lastVerified='2026-09-19',
    ),
}
