/* Tier A — the Firefox image job's probes EXECUTED against a real DOM (jsdom).

   RULE 8: every script is generated by the REAL Python builders
   (`app/browser/uivision/job_probes.py` / `job_submit_probes.py`, rendered the
   way the extension renders them — the payload as an inline JSON literal, the
   budget as `${!cmd_var1}`), and run exactly as Ui.Vision's executeScript runs
   it: `Promise.resolve((function () { BODY })())`.

   Covered: the composer state (clean vs. still busy), the native-click locator
   (xpath), the attachment proof (one NEW tile named like the sent file, stale
   tiles refused, wrong files refused), the prompt insert + read-back (React-safe
   setter, truncation refused, FNV-1a read across the boundary), the submit guard
   (enabled Send only, security dialog blocks), the result correlation (baseline,
   own message, ambiguity, timeout) and the in-page byte fetch.

   The markup is the owner's page shape: `div.flex.flex-wrap.gap-2` attachment
   strip with `img[alt]` tiles, `textarea[name="message"]` in a form, a Send
   button with `aria-label="Send message"` and result images with
   `class="aspect-square cursor-pointer"` inside `div.no-scrollbar`. */

import { test, describe, before } from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { JSDOM } from 'jsdom';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');

const PROMPT = 'héllo\nworld 🎨 [JOB-ID: T1]';
const PY_GEN = `
import json
from app.browser.uivision import job_macro as jm, job_probes, job_submit_probes
base = dict(token="T1", image_path="/tmp/pics/a.png", file_name="a.png", prompt=${JSON.stringify(PROMPT)},
            baseline=["https://cdn/old.png"])
def payload(stage, **extra):
    fields = dict(base, **extra)
    fields.update(stage=stage)
    return jm.payload(jm.StageInputs(**fields))
out = {
  "payload": json.loads(payload("prepare")),
  "state": job_probes.render_state_js(payload("prepare"), 4000),
  "stateClean": job_probes.render_state_js(payload("newchat"), 4000),
  "locate": job_probes.render_locate_js(payload("prepare", extra={"list": ["button[aria-label=\\"Add files\\"]"],
                                                                 "pick": "first", "key": "attach"}), 1000),
  "attach": job_probes.render_attach_js(payload("prepare"), 1500),
  "attachAfterCleanup": job_probes.render_attach_js(
      payload("prepare", extra={"before": ["b.png|blob:https://arena.ai/9"]}), 800),
  "fetch": job_probes.render_fetch_js(payload("submit", src="https://cdn/new.png"), 4000),
  "prompt": job_submit_probes.render_prompt_js(payload("submit"), 4000),
  "guard": job_submit_probes.render_guard_js(payload("submit"), 4000),
  "why": job_submit_probes.render_guard_why_js(payload("submit"), 4000),
  "result": job_submit_probes.render_result_js(payload("submit"), 2500),
  "resultFast": job_submit_probes.render_result_js(payload("submit"), 700),
}
print(json.dumps(out))
`;

function findPython() {
  const cands = [process.env.PYTHON, path.join(ROOT, '.venv/bin/python'),
    path.join(ROOT, '.venv/Scripts/python.exe'), '/home/user/.venv/bin/python',
    'python3', 'python'].filter(Boolean);
  for (const c of cands) {
    try { execFileSync(c, ['-c', 'import sys'], { stdio: 'ignore' }); return c; } catch { /* next */ }
  }
  assert.fail('no Python interpreter found — set PYTHON=<path>');
}

let JS;
before(() => {
  JS = JSON.parse(execFileSync(findPython(), ['-c', PY_GEN], { cwd: ROOT, encoding: 'utf-8' }));
});

function page(body) {
  const dom = new JSDOM(`<!doctype html><html><body>${body}</body></html>`,
    { runScripts: 'outside-only', pretendToBeVisual: true });
  const win = dom.window;
  Object.defineProperty(win.HTMLElement.prototype, 'offsetParent', {
    get() { return this.parentElement; }, configurable: true,
  });
  win.Element.prototype.getBoundingClientRect = function () {
    const w = Number(this.getAttribute?.('data-w') ?? 120);
    const h = Number(this.getAttribute?.('data-h') ?? 20);
    return { left: 0, top: 0, right: w, bottom: h, width: w, height: h };
  };
  Object.defineProperty(win.HTMLImageElement.prototype, 'naturalWidth', {
    get() { return Number(this.getAttribute('width') || 0); }, configurable: true,
  });
  Object.defineProperty(win.HTMLImageElement.prototype, 'naturalHeight', {
    get() { return Number(this.getAttribute('height') || 0); }, configurable: true,
  });
  return win;
}

async function run(win, js) {
  const raw = await win.eval(`Promise.resolve((function () { ${js} })())`);
  return typeof raw === 'string' && raw.startsWith('{') ? JSON.parse(raw) : raw;
}

const COMPOSER = (extra = '') => `<form>`
  + `<textarea name="message" rows="1"></textarea>`
  + `<button type="button" aria-label="Add files">+</button>`
  + `<button type="button" aria-label="Send message"${extra}>Send</button></form>`;

const TILE = (alt, src, remove = true) => `<div class="flex flex-wrap gap-2"><div>`
  + `<img alt="${alt}" src="${src}" width="60" height="60">`
  + (remove ? `<button type="button" aria-label="Remove file">x</button>` : '')
  + `</div></div>`;

const OUTPUT = (src, w = 900, inner = '') =>
  `<div class="no-scrollbar">${inner}<img class="aspect-square cursor-pointer" src="${src}" width="${w}" height="${w}"></div>`;

const CONVO = (token = 'T1', result = 'https://cdn/new.png') =>
  `<div class="group flex"><div class="items-end">old question</div>`
  + `<div class="items-end">${token} prompt text</div></div>`
  + `<div class="group flex"><div class="flex flex-col"><div>answer</div>${OUTPUT(result)}</div></div>`;

describe('Firefox image-job probes', () => {
  test('state: an empty composer on a fresh chat is clean, an attachment is not', async () => {
    const win = page(COMPOSER() + '<a href="/image/direct">New Chat</a>');
    const state = await run(win, JS.state);
    assert.equal(state.textarea, true);
    assert.equal(state.clean, true);
    assert.equal(state.send, true);
    const busy = page(COMPOSER() + TILE('a.png', 'blob:https://arena.ai/1'));
    const dirty = await run(busy, JS.stateClean);
    assert.equal(dirty.clean, false);
    assert.equal(dirty.previews.length, 1);
    assert.equal(dirty.previews[0].alt, 'a.png');
  });

  test('locate: the Add files button comes back as an xpath the extension can click', async () => {
    const win = page(COMPOSER());
    const reply = await run(win, JS.locate);
    assert.equal(reply.ok, true);
    assert.match(reply.loc, /^xpath=\/html\[1\]\//);
    assert.equal(reply.key, 'attach');
  });

  test('attach: exactly one NEW tile named like the sent file is the pass', async () => {
    const win = page(COMPOSER() + TILE('a.png', 'blob:https://arena.ai/2'));
    const reply = await run(win, JS.attach);
    assert.equal(reply.ok, true);
    assert.equal(reply.found.alt, 'a.png');
    assert.equal(reply.count, 1);
  });

  test('attach: a tile from a previous job is refused, never ridden along', async () => {
    const win = page(COMPOSER() + TILE('b.png', 'blob:https://arena.ai/9'));
    const reply = await run(win, JS.attach);
    assert.equal(reply.ok, false);
    assert.match(reply.reason, /wrong file attached: b\.png/);

    // …and when the app already knows the page held that tile, the refusal says
    // exactly why (the baseline it was given) with the stale count
    const known = page(COMPOSER() + TILE('b.png', 'blob:https://arena.ai/9'));
    const refused = await run(known, JS.attachAfterCleanup);
    assert.equal(refused.ok, false);
    assert.match(refused.reason, /stale attachment from a previous job \(b\.png\)/);
    assert.equal(refused.stale, 1);
  });

  test('attach: a tile we did not send (wrong file) is refused by name', async () => {
    const win = page(COMPOSER() + TILE('other.png', 'blob:https://arena.ai/3'));
    const reply = await run(win, JS.attach);
    assert.equal(reply.ok, false);
    assert.match(reply.reason, /wrong file attached: other\.png/);
  });

  test('attach: a second tile appearing with ours refuses the whole attach', async () => {
    const win = page(COMPOSER() + TILE('a.png', 'blob:https://arena.ai/1')
      + TILE('b.png', 'blob:https://arena.ai/2'));
    const reply = await run(win, JS.attach);
    assert.equal(reply.ok, false);
    assert.match(reply.reason, /2 attachments appeared — expected exactly 1/);
    assert.match(reply.reason, /stale tile from an earlier job/);
  });

  test('attach: a security dialog stops the proof before anything is submitted', async () => {
    const win = page(COMPOSER()
      + '<div role="dialog" data-state="open">Security Verification</div>'
      + TILE('a.png', 'blob:https://arena.ai/4'));
    const reply = await run(win, JS.attach);
    assert.equal(reply.ok, false);
    assert.equal(reply.security, true);
  });

  test('prompt: the React-safe setter writes the exact multiline Unicode prompt', async () => {
    const win = page(COMPOSER());
    const reply = await run(win, JS.prompt);
    assert.equal(reply.ok, true);
    assert.equal(reply.len, PROMPT.length);
    assert.equal(reply.hash, reply.expected_hash);
    assert.equal(win.document.querySelector('textarea').value, PROMPT);
  });

  test('prompt: a truncated read-back is refused after the bounded retries', async () => {
    const win = page(COMPOSER());
    const ta = win.document.querySelector('textarea');
    ta.addEventListener('input', () => { ta.value = ta.value.slice(0, 4); });
    const reply = await run(win, JS.prompt);
    assert.equal(reply.ok, false);
    assert.match(reply.reason, /truncated read-back/);
    assert.notEqual(reply.hash, reply.expected_hash);
  });

  test('guard: passes only with the exact prompt, one named tile and an enabled Send', async () => {
    const win = page(COMPOSER() + TILE('a.png', 'blob:https://arena.ai/5'));
    const ta = win.document.querySelector('textarea');
    ta.value = PROMPT;
    assert.equal(await run(win, JS.guard), 'true');
    assert.equal(await run(win, JS.why), 'ready');
  });

  test('guard: a disabled Send is a refusal with its own sentence', async () => {
    const win = page(COMPOSER(' disabled') + TILE('a.png', 'blob:https://arena.ai/6'));
    win.document.querySelector('textarea').value = PROMPT;
    assert.equal(await run(win, JS.guard), 'false');
    assert.match(await run(win, JS.why), /send button disabled/);
  });

  test('guard: a security dialog is a refusal before the click', async () => {
    const win = page(COMPOSER() + TILE('a.png', 'blob:https://arena.ai/7')
      + '<div role="dialog" data-state="open">Security Verification</div>');
    win.document.querySelector('textarea').value = PROMPT;
    assert.equal(await run(win, JS.guard), 'false');
    assert.match(await run(win, JS.why), /security dialog visible/);
  });

  test('result: the candidate after this job’s own message is the correlated one', async () => {
    const win = page(COMPOSER() + CONVO());
    const reply = await run(win, JS.result);
    assert.equal(reply.ok, true);
    assert.equal(reply.candidates[0].src, 'https://cdn/new.png');
    assert.equal(reply.candidates[0].after, true);
    assert.equal(reply.candidates[0].in_user, false);
    assert.equal(reply.candidates[0].large, true);
    assert.equal(reply.token_seen, true);
  });

  test('result: an image from before this job is filtered by the baseline', async () => {
    const win = page(COMPOSER() + CONVO('T1', 'https://cdn/old.png'));
    const reply = await run(win, JS.result);
    assert.equal(reply.ok, false);                       // the only image is the baseline one
    assert.equal(reply.candidates.length, 0);
    assert.equal(reply.token_seen, true);
  });

  test('result: an image inside this job’s own message is flagged, not claimed', async () => {
    const win = page(COMPOSER() + CONVO()
      .replace('<div class="items-end">T1 prompt text</div>',
        '<div class="items-end">T1 prompt text'
        + '<img class="aspect-square cursor-pointer" src="https://cdn/me.png" width="900" height="900">'
        + '</div>'));
    const reply = await run(win, JS.result);
    const own = reply.candidates.find((c) => c.src === 'https://cdn/me.png');
    const answer = reply.candidates.find((c) => c.src === 'https://cdn/new.png');
    assert.equal(own.in_user, true);                 // `correlate()` filters exactly this one
    assert.equal(own.after, false);
    assert.equal(answer.in_user, false);
    assert.equal(answer.after, true);
  });

  test('result: two large candidates are reported, never silently chosen', async () => {
    const win = page(COMPOSER() + CONVO()
      + '<div class="group flex"><div class="flex flex-col">' + OUTPUT('https://cdn/second.png', 800)
      + '</div></div>');
    const reply = await run(win, JS.result);
    assert.equal(reply.candidates.length, 2);
    assert.equal(reply.ok, true);                        // the app decides: correlate() says ambiguous
  });

  test('result: a clean page times out with the token still on it', async () => {
    const win = page(COMPOSER() + '<div class="group flex"><div class="items-end">T1 prompt</div></div>');
    const reply = await run(win, JS.resultFast);
    assert.equal(reply.ok, false);
    assert.equal(reply.timed_out, true);
    assert.equal(reply.token_seen, true);
  });

  test('fetch: the page hands back the image bytes as base64', async () => {
    const win = page(COMPOSER() + OUTPUT('https://cdn/new.png'));
    win.fetch = async () => ({ ok: true, arrayBuffer: async () => new Uint8Array([1, 2, 3, 250]).buffer });
    const reply = await run(win, JS.fetch);
    assert.equal(reply.ok, true);
    assert.equal(reply.method, 'fetch');
    assert.equal(reply.b64, win.btoa(String.fromCharCode(1, 2, 3, 250)));
    assert.equal(Number(reply.len), reply.b64.length);
  });

  test('fetch: a failed fetch falls back to the page image and names its own failure', async () => {
    const win = page(COMPOSER() + OUTPUT('https://cdn/new.png'));
    win.fetch = async () => { throw new Error('blocked by CORS'); };
    const reply = await run(win, JS.fetch);
    assert.equal(reply.ok, false);                       // jsdom has no canvas: named, never silent
    assert.match(reply.note, /blocked by CORS/);
  });
});
