/* Tier A — the AWAIT_PROCESSING_IMAGE processing-indicator probe, executed
   for real in jsdom (Node.js, no browser).

   RULE 8: the probe JS is generated by the REAL Python builder
   (app/browser/processing_probe.py — this file shells out to Python for the
   exact payload the runner sends through Runtime.evaluate) and runs against
   a real DOM tree.

   Regression (bugfix-verification.md §B12): the block never had a probe of
   its own — it ran the WAIT_OUTPUT "new output image" wait, which on an idle
   page can only end by timeout; before ATTACH_IMAGE that was the 120 s
   "waits for a generation that never starts" first run. The contract here:
   an idle page (old outputs, the word "processing" inside the user's prompt,
   a hidden spinner) answers `processing:false`; a visible spinner / label /
   aria-busy answers `true`. */

import { test, describe, before } from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import vm from 'node:vm';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { JSDOM } from 'jsdom';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');

const PY_GEN = `
import json
from app.browser.processing_probe import build_processing_probe
from app.browser.probe_selectors import spinner_selector
from app.core.action_blocks import BLOCK_DEFINITIONS
sel = BLOCK_DEFINITIONS["AWAIT_PROCESSING_IMAGE"]["default_selector"]
text = BLOCK_DEFINITIONS["AWAIT_PROCESSING_IMAGE"]["default_match_text"]
print(json.dumps({
  "default": build_processing_probe(sel, text),
  "bare": build_processing_probe("", ""),
  "invalid_part": build_processing_probe("div:nonexistent-pseudo, .spinner", ""),
  "spinner": spinner_selector(),
}))
`;

function findPython() {
  const cands = [process.env.PYTHON, path.join(ROOT, '.venv/bin/python'), path.join(ROOT, '.venv/Scripts/python.exe'),
    '/home/user/.venv/bin/python', 'python3', 'python'].filter(Boolean);
  for (const c of cands) {
    try { execFileSync(c, ['-c', 'import sys'], { stdio: 'ignore' }); return c; } catch { /* next */ }
  }
  assert.fail('no Python interpreter found — set PYTHON=<path> (the probe is generated by app/browser/processing_probe.py)');
}

let GEN;
before(() => {
  GEN = JSON.parse(execFileSync(findPython(), ['-c', PY_GEN], { cwd: ROOT, encoding: 'utf-8' }));
});

/* jsdom has no layout: give it the two facts the probe's visibility check
   reads — an element hidden by [hidden] / display:none / .hidden (or inside
   one) has no offsetParent and an empty rect; everything else is 10×10. */
function run(html, which = 'default') {
  const dom = new JSDOM(`<body>${html}</body>`, { pretendToBeVisual: true });
  const w = dom.window;
  const hiddenOf = (el) => {
    for (let e = el; e; e = e.parentElement) {
      if (e.hidden || e.style.display === 'none' || e.classList.contains('hidden')) return true;
    }
    return false;
  };
  Object.defineProperty(w.HTMLElement.prototype, 'offsetParent', {
    get() { return hiddenOf(this) ? null : this.ownerDocument.body; }, configurable: true,
  });
  w.HTMLElement.prototype.getBoundingClientRect = function () {
    const h = hiddenOf(this);
    return { x: 0, y: 0, top: 0, left: 0, width: h ? 0 : 10, height: h ? 0 : 10, right: 10, bottom: 10 };
  };
  const raw = vm.runInContext(GEN[which], vm.createContext(w));
  assert.equal(typeof raw, 'string', 'probe returns a JSON string');
  return JSON.parse(raw);
}

const IDLE_PAGE = `
  <main>
    <div class="msg user">Please keep processing this image carefully and return a red circle version of it, thanks</div>
    <div class="flex"><div class="h-5 w-5 animate-spin" style="display:none"><canvas></canvas></div><span>Response A</span></div>
    <div class="no-scrollbar"><img src="https://x.r2.cloudflarestorage.com/old.png"></div>
    <textarea name="message">Processing</textarea>
    <button aria-label="Send message">Send</button>
    <div class="spinner hidden"></div>
  </main>`;

describe('processing probe — payload', () => {
  test('parses as a script and never sends :has-text() to querySelectorAll', () => {
    for (const k of ['default', 'bare', 'invalid_part']) new vm.Script(GEN[k]);
    assert.ok(!GEN.default.includes(':has-text'), 'Playwright syntax translated into {sel,text} parts');
    assert.ok(GEN.default.includes(JSON.stringify(GEN.spinner)), 'site adapter spinner wired in');
  });
});

describe('processing probe — idle pages answer false at once', () => {
  test('old outputs + "processing" inside the prompt + hidden spinners → idle', () => {
    const r = run(IDLE_PAGE);
    assert.equal(r.processing, false);
    assert.deepEqual(r.indicators, []);
    assert.deepEqual(r.skipped, []);
  });

  test('empty body → idle (no crash on a page without content)', () => {
    assert.equal(run('').processing, false);
  });

  test('bare probe (no block selector, no text) still checks the site spinner only', () => {
    assert.equal(run('<div>Processing…</div>', 'bare').processing, false);
    assert.equal(run('<div class="animate-spin"></div>', 'bare').processing, true);
  });

  test('a long sentence that merely contains the word never counts', () => {
    const r = run('<p>Processing is what I asked for in the prompt but this sentence is far too long to be a status label</p>');
    assert.equal(r.processing, false);
  });
});

describe('processing probe — busy pages answer true with the indicator', () => {
  test('visible site spinner (Response A/B row)', () => {
    const r = run(`<div class="flex"><div class="h-5 w-5 animate-spin"><canvas></canvas></div><span>Response A</span></div>`);
    assert.equal(r.processing, true);
    assert.equal(r.indicators[0].kind, 'spinner');
    assert.equal(r.indicators[0].sel, GEN.spinner);
  });

  test('div:has-text("Processing") label — own text', () => {
    const r = run('<div>Processing…</div>');
    assert.equal(r.processing, true);
    assert.ok(r.indicators.some((i) => i.kind === 'selector' && i.sel === 'div' && i.text === 'processing'));
  });

  test('div:has-text("Generating") — small wrapper around a span', () => {
    const r = run('<div class="row"><span>Generating…</span></div>');
    assert.equal(r.processing, true);
    assert.ok(r.indicators.some((i) => i.kind === 'selector' && i.text === 'generating'));
  });

  test('[aria-busy="true"] container', () => {
    const r = run('<section aria-busy="true"><p>streaming</p></section>');
    assert.equal(r.processing, true);
    assert.equal(r.indicators[0].sel, '[aria-busy="true"]');
  });

  test('match_text: a short text node that STARTS with it, any element', () => {
    const r = run('<span class="status">Processing image 1 of 3</span>');
    assert.equal(r.processing, true);
    assert.deepEqual(r.indicators[0], { kind: 'text', sel: 'span', text: 'Processing image 1 of 3' });
  });

  test('hidden indicators do not count (display:none, [hidden], .hidden ancestor)', () => {
    assert.equal(run('<div class="spinner" hidden></div>').processing, false);
    assert.equal(run('<div style="display:none"><div class="animate-spin"></div></div>').processing, false);
    assert.equal(run('<div class="hidden"><span>Processing…</span></div>').processing, false);
  });

  test('a selector part the browser rejects is skipped, the rest still works', () => {
    const r = run('<div class="spinner"></div>', 'invalid_part');
    assert.equal(r.processing, true);
    assert.deepEqual(r.skipped, ['div:nonexistent-pseudo']);
  });
});
