/* Tier A — the Firefox image job's page scripts, executed for real in jsdom.

   RULE 8: every body AND the base64 loader Target are generated by the REAL
   Python builders (app/browser/uivision/job_scripts.py + job_macros.py — this
   file shells out to Python for the exact strings the phase macros carry)
   and run against a real DOM tree, the way Ui.Vision's executeScript runs
   them: the Target is the body of an anonymous function whose return value
   (a Promise of the JSON reply) is echoed into the savelog.

   Contract (design 2026-09-25-firefox-image-job §4/§6): prompt readback is
   exact + SHA-256 (the same hash Python computes), a preview counts only by
   the unique staged name, the submit guard refuses when the JOB-ID bubble
   already exists, the ack tells a bubble from a cleared composer, New Chat
   is clean only when the composer is visible + empty with no preview. */

import { test, describe, before } from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { webcrypto } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { JSDOM } from 'jsdom';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');
const PROMPT = '[JOB-ID: c1]\nŽluťoučký kůň 😀 ${x} `tick`';

const PY_GEN = `
import json, sys
from app.browser.uivision import job_scripts as js, job_macros as jm
from app.services.firefox_job_phases import sha_of, utf16_len
p = sys.argv[1]
base = {"srcs": ["https://r2/old.png"], "outputs": []}
bodies = {
  "baseline": js.baseline_js(False), "attach": js.attach_wait_js("arena_c1.png", 50),
  "prompt": js.prompt_js(p), "guard": js.guard_js("c1", sha_of(p), "arena_c1.png"),
  "ack": js.ack_js("c1", 50), "clean": js.clean_js(50), "security": js.security_js(False),
  "observe": js.observe_js("c1", base, 0, False), "boom": "(() => { throw new Error('kaput'); })()",
}
print(json.dumps({"targets": {k: jm.loader("c1", k, v) for k, v in bodies.items()},
                  "sha": sha_of(p), "len": utf16_len(p)}))
`;

function findPython() {
  const cands = [process.env.PYTHON, path.join(ROOT, '.venv/bin/python'), path.join(ROOT, '.venv/Scripts/python.exe'),
    '/home/user/.venv/bin/python', 'python3', 'python'].filter(Boolean);
  for (const c of cands) {
    try { execFileSync(c, ['-c', 'import sys'], { stdio: 'ignore' }); return c; } catch { /* next */ }
  }
  assert.fail('no Python interpreter found — set PYTHON=<path> (the scripts are generated by job_scripts.py)');
}

let GEN;
before(() => {
  GEN = JSON.parse(execFileSync(findPython(), ['-c', PY_GEN, PROMPT], { cwd: ROOT, encoding: 'utf-8' }));
});

/* jsdom has no layout: an element hidden by [hidden] / display:none (or inside
   one) has no offsetParent; everything else is "visible". */
function page(html) {
  const dom = new JSDOM(`<body>${html}</body>`, { pretendToBeVisual: true, runScripts: 'outside-only' });
  const w = dom.window;
  const hidden = (el) => { for (let e = el; e; e = e.parentElement) { if (e.hidden || e.style.display === 'none') return true; } return false; };
  Object.defineProperty(w.HTMLElement.prototype, 'offsetParent', {
    get() { return hidden(this) ? null : this.ownerDocument.body; }, configurable: true,
  });
  Object.defineProperty(w, 'crypto', { value: webcrypto, configurable: true });
  Object.assign(w, { TextEncoder, TextDecoder });
  return w;
}

/* Ui.Vision executeScript: the Target is a function body; its return value is awaited. */
async function run(w, which) {
  const raw = await w.eval(`(function () { ${GEN.targets[which]} })()`);
  assert.equal(typeof raw, 'string', 'the loader always answers a JSON string');
  const reply = JSON.parse(raw);
  assert.equal(reply.token, 'c1');
  assert.equal(reply.phase, which);
  return reply.data;
}

const COMPOSER = (value = '') => `<form><div class="flex flex-wrap gap-2">__PREVIEWS__</div>
  <textarea name="message">${value}</textarea>
  <button aria-label="Send message">Send</button></form>`;
const withPreview = (alt) => COMPOSER().replace('__PREVIEWS__', alt ? `<img alt="${alt}" src="blob:x">` : '');

describe('firefox job — prompt', () => {
  test('inserts, reads back exactly, and hashes like Python (UTF-16 length)', async () => {
    const w = page(withPreview(''));
    const r = await run(w, 'prompt');
    assert.equal(r.ok, true, r.error);
    assert.equal(r.len, GEN.len);
    assert.equal(r.sha256, GEN.sha);
    assert.equal(w.document.querySelector('textarea').value, PROMPT);
  });

  test('no composer → honest error, never ok', async () => {
    const r = await run(page('<main></main>'), 'prompt');
    assert.equal(r.ok, false);
    assert.equal(r.len, -1);
    assert.match(r.error, /textarea/);
  });
});

describe('firefox job — attachment', () => {
  test('matches the unique staged name only', async () => {
    assert.equal((await run(page(withPreview('arena_c1.png')), 'attach')).matched, 1);
    const other = await run(page(withPreview('someone.png')), 'attach');
    assert.equal(other.matched, 0);
    assert.deepEqual(other.previews.map((p) => p.alt), ['someone.png']);
  });

  test('a hidden preview does not count', async () => {
    const w = page(withPreview('arena_c1.png'));
    w.document.querySelector('img').style.display = 'none';
    assert.deepEqual((await run(w, 'attach')).previews, []);
  });
});

describe('firefox job — submit guard + ack', () => {
  test('guard: our prompt + our preview + send enabled → go', async () => {
    const w = page(withPreview('arena_c1.png'));
    w.document.querySelector('textarea').value = PROMPT;
    const g = await run(w, 'guard');
    assert.deepEqual([g.go, g.promptOk, g.attachmentOk, g.sendEnabled, g.bubble], [true, true, true, true, false]);
  });

  test('guard: the JOB-ID bubble already on the page → never click again', async () => {
    const w = page(withPreview('arena_c1.png') + '<div class="msg">[JOB-ID: c1] sent</div>');
    w.document.querySelector('textarea').value = PROMPT;
    const g = await run(w, 'guard');
    assert.equal(g.go, false);
    assert.equal(g.bubble, true);
  });

  test('guard: wrong prompt or disabled send → no go', async () => {
    const w = page(withPreview('arena_c1.png'));
    w.document.querySelector('textarea').value = 'something else';
    w.document.querySelector('button').disabled = true;
    const g = await run(w, 'guard');
    assert.deepEqual([g.go, g.promptOk, g.sendEnabled], [false, false, false]);
  });

  test('ack: bubble beats a cleared composer; a kept prompt is no ack', async () => {
    const bubble = page(withPreview('') + '<p>[JOB-ID: c1] hello</p>');
    assert.equal((await run(bubble, 'ack')).ack, 'bubble');
    assert.equal((await run(page(withPreview('')), 'ack')).ack, 'cleared');
    const kept = page(withPreview(''));
    kept.document.querySelector('textarea').value = PROMPT;
    assert.equal((await run(kept, 'ack')).ack, '');
  });
});

describe('firefox job — New Chat clean page', () => {
  test('visible empty composer without preview → clean', async () => {
    const r = await run(page(withPreview('')), 'clean');
    assert.equal(r.clean, true, JSON.stringify(r.state));
  });

  test('leftover text or preview → not clean (within the budget)', async () => {
    const w = page(withPreview('old.png'));
    w.document.querySelector('textarea').value = 'left';
    const r = await run(w, 'clean');
    assert.equal(r.clean, false);
    assert.deepEqual([r.state.empty, r.state.previews], [false, 1]);
  });
});

describe('firefox job — baseline / observe / security / loader', () => {
  test('baseline reports composer + previews + old outputs', async () => {
    const b = await run(page(withPreview('')), 'baseline');
    assert.equal(b.composer_len, 0);
    assert.deepEqual(b.previews, []);
    assert.ok(Array.isArray(b.srcs) && Array.isArray(b.outputs));
    assert.equal(b.security, false);
  });

  test('observe (window 0) answers once with the composer hash', async () => {
    const w = page(withPreview('arena_c1.png'));
    w.document.querySelector('textarea').value = PROMPT;
    const o = await run(w, 'observe');
    assert.equal(o.found, false);
    assert.equal(o.composer_sha, GEN.sha);
    assert.deepEqual(o.previews.map((p) => p.alt), ['arena_c1.png']);
  });

  test('security probe is constant false while the Watcher is off (RULE 20)', async () => {
    assert.deepEqual(await run(page(''), 'security'), { security: false });
  });

  test('a throwing body comes back as the loader error reply', async () => {
    const r = await run(page(''), 'boom');
    assert.equal(r.ok, false);
    assert.match(r.error, /kaput/);
  });
});

/* Audit B3 (2026-09-26): Chrome's insert writes into the FIRST VISIBLE textarea of
   textarea_selectors(); every read (readback, guard, observe, clean) must see that
   same element — a hidden primary must not shadow the visible fallback. */
const HIDDEN_PRIMARY = (value = '') => `<form><div class="flex flex-wrap gap-2"></div>
  <textarea name="message" hidden>stale draft</textarea>
  <textarea placeholder="Describe the image">${value}</textarea>
  <button aria-label="Send message">Send</button></form>`;

describe('firefox job — composer = the element the insert writes (B3)', () => {
  test('readback sees the visible fallback, not a hidden primary', async () => {
    const w = page(HIDDEN_PRIMARY());
    const r = await run(w, 'prompt');
    assert.equal(r.ok, true, r.error);
    assert.equal(r.sha256, GEN.sha);
    assert.equal(w.document.querySelector('textarea[placeholder]').value, PROMPT);
  });

  test('the guard reads the same element', async () => {
    const w = page(HIDDEN_PRIMARY().replace('__NOPE__', ''));
    w.document.querySelector('textarea[placeholder]').value = PROMPT;
    const g = await run(w, 'guard');
    assert.equal(g.promptOk, true);
  });

  test('New Chat is clean when the visible composer is empty', async () => {
    const c = await run(page(HIDDEN_PRIMARY()), 'clean');
    assert.equal(c.clean, true, JSON.stringify(c.state));
  });
});
