/* Tier A — the Firefox identify payload EXECUTED against a real DOM (jsdom).

   RULE 8: the script is generated by the REAL Python builder
   (app/browser/uivision/identify.py `render_identify_js` — the extension's
   JSON.stringify rendering of `${!cmd_var1..2}`) and run the way Ui.Vision's
   executeScript runs it: `Promise.resolve((function () { BODY })())`.
   The sidebar markup is the owner's page evidence:
   <div class="font-heading min-w-0 flex-1 truncate text-left text-sm font-normal">
   Covered: success, delayed load, missing element (fallback name), stale
   overlay replacement, no duplicates on re-run, clear-only runs. */

import { test, describe, before } from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { JSDOM } from 'jsdom';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');

const PY_GEN = `
import json
from app.browser.uivision import identify
print(json.dumps({
  "first": identify.render_identify_js(2, "Profile1"),
  "third": identify.render_identify_js(3, "Profile1"),
  "clear": identify.render_identify_js(0, "", clear=True),
}))
`;

function findPython() {
  const cands = [process.env.PYTHON, path.join(ROOT, '.venv/bin/python'),
    path.join(ROOT, '.venv/Scripts/python.exe'), 'python3', 'python'].filter(Boolean);
  for (const c of cands) {
    try { execFileSync(c, ['-c', 'import sys'], { stdio: 'ignore' }); return c; } catch { /* next */ }
  }
  assert.fail('no Python interpreter found — set PYTHON=<path>');
}

let JS;
before(() => {
  JS = JSON.parse(execFileSync(findPython(), ['-c', PY_GEN], { cwd: ROOT, encoding: 'utf-8' }));
});

const ACCOUNT = '<div class="font-heading min-w-0 flex-1 truncate text-left text-sm font-normal">'
  + 'mailreceiverpro@gmail.com</div>';
const SIDEBAR = (inner) => `<div data-sidebar="sidebar"><ul data-sidebar="menu"><button>`
  + `<div class="flex"><span class="rounded-full"><img alt=""></span>${inner}</div>`
  + `</button></ul></div><main><textarea name="message">not@this.one</textarea></main>`;

function page(body) {
  const dom = new JSDOM(`<!doctype html><html><body>${body}</body></html>`, { runScripts: 'outside-only' });
  dom.window.Element.prototype.getBoundingClientRect = () => ({ left: 0, top: 0, width: 120, height: 20 });
  return dom.window;
}

const fast = (js, ms) => js.replace('parseInt("8000", 10)', `parseInt("${ms}", 10)`);

async function run(win, js) {
  const raw = await win.eval(`Promise.resolve((function () { ${js} })())`);
  return JSON.parse(raw);
}

const badges = (win) => [...win.document.querySelectorAll('[data-arena-worker]')];

describe('Firefox identify payload', () => {
  test('success: reads the account and draws ONE centered, click-through overlay', async () => {
    const win = page(SIDEBAR(ACCOUNT));
    const reply = await run(win, JS.first);
    assert.equal(reply.email, 'mailreceiverpro@gmail.com');
    assert.equal(reply.overlay, 'ok');
    assert.equal(reply.text, '2# mailreceiverpro@gmail.com');
    const all = badges(win);
    assert.equal(all.length, 1);
    assert.equal(all[0].textContent, '2#mailreceiverpro@gmail.com');
    assert.match(all[0].style.cssText, /pointer-events: none/);
    assert.match(all[0].style.cssText, /left: 50%/);
    assert.match(all[0].style.cssText, /position: fixed/);
    assert.equal(all[0].getAttribute('data-arena-worker'), '2');
    assert.equal(reply.candidates, undefined);           // no page text in the reply
  });

  test('delayed load: the account row appears after the script started', async () => {
    const win = page(SIDEBAR(''));
    setTimeout(() => {
      win.document.querySelector('div.flex').insertAdjacentHTML('beforeend', ACCOUNT);
    }, 500);
    const reply = await run(win, fast(JS.first, 3000));
    assert.equal(reply.email, 'mailreceiverpro@gmail.com');
    assert.equal(badges(win)[0].textContent, '2#mailreceiverpro@gmail.com');
  });

  test('missing element: bounded wait, then the fallback name is drawn', async () => {
    const win = page(SIDEBAR(''));
    const t0 = Date.now();
    const reply = await run(win, fast(JS.first, 600));
    assert.ok(Date.now() - t0 >= 550, 'waited the budget');
    assert.equal(reply.email, '');
    assert.equal(reply.text, '2# Profile1');
    assert.equal(badges(win)[0].textContent, '2#Profile1');
  });

  test('fallback: class names changed — the avatar-sibling structure still finds it', async () => {
    const win = page(SIDEBAR('<div class="x-new-name">mailreceiverpro@gmail.com</div>'));
    const reply = await run(win, fast(JS.first, 0));
    assert.equal(reply.email, 'mailreceiverpro@gmail.com');
    assert.equal(reply.via, 'scope');       // a site_adapter selector, not the loose text scan
  });

  test('the composer never labels a tab', async () => {
    const win = page('<main><textarea>someone@else.com</textarea></main>');
    const reply = await run(win, fast(JS.first, 0));
    assert.equal(reply.email, '');
  });

  test('stale overlay is replaced, never duplicated, when the number changes', async () => {
    const win = page(SIDEBAR(ACCOUNT)
      + '<div data-arena-worker="7">7# old@name.io</div><div data-arena-worker="7">dup</div>');
    await run(win, JS.first);
    await run(win, JS.third);
    const all = badges(win);
    assert.equal(all.length, 1);
    assert.equal(all[0].textContent, '3#mailreceiverpro@gmail.com');
  });

  test('clear-only run removes the overlay without probing', async () => {
    const win = page(SIDEBAR(ACCOUNT) + '<div data-arena-worker="2">2# x</div>');
    const reply = await run(win, JS.clear);
    assert.equal(reply.email, '');
    assert.equal(reply.overlay, 'ok');
    assert.equal(badges(win).length, 0);
  });
});
