/* Tier A — the FIND / CLICK / HIGHLIGHT / CLEAR page probes (Node.js, no browser).

   RULE 8: the probes are generated by the REAL Python builders
   (app/browser/dom_highlight.py → dom_highlight_js.py) — this file shells out
   to Python for the exact JS the app sends through Runtime.evaluate — and are
   executed against a stub document.

   Regression (bugfix-verification.md §B9): `_LABEL_JS` lost the closing brace
   of `if (childSel) { … }`, so EVERY find/highlight probe was a SyntaxError
   ("Unexpected token 'catch'") — every visual click (Submit, Find & Click,
   New Chat reset), VERIFY_ATTACHMENT and every HIGHLIGHT block failed with
   "no data returned from the page". Nothing executed the generated JS. */

import { test, describe, before } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');

const PY_GEN = `
import json
from app.browser.dom_highlight import build_find_probe, build_click_probe, build_highlight_probe, build_clear_probe
from app.browser.probe_requests import FindProbeSpec, ClickProbeSpec, HighlightSpec, MATCH_EXACT, MATCH_CONTAINS
out = {
  "find_plain": build_find_probe("button", FindProbeSpec(highlight=True, highlight_ms=10)),
  "find_no_hl": build_find_probe("button", FindProbeSpec(highlight=False)),
  "find_label_contains": build_find_probe("button", FindProbeSpec(label_selector="span", match_text="New Chat", match_mode=MATCH_CONTAINS, highlight=False)),
  "find_label_exact": build_find_probe("button", FindProbeSpec(label_selector="span", match_text="New Chat", match_mode=MATCH_EXACT, highlight=False)),
  "find_text_exact_nolabel": build_find_probe("button", FindProbeSpec(match_text="Send", match_mode=MATCH_EXACT, highlight=False)),
  "click_stage": build_click_probe(None, ClickProbeSpec(highlight=True, highlight_ms=10, do_click=False)),
  "click_go": build_click_probe(None, ClickProbeSpec(highlight=False, do_click=True)),
  "click_inner": build_click_probe("svg", ClickProbeSpec(highlight=False, do_click=True)),
  "highlight": build_highlight_probe("button", HighlightSpec(label_selector="span", match_text="New", clear_first=True, highlight_ms=10)),
  "clear": build_clear_probe(),
}
print(json.dumps(out))
`;

function findPython() {
  const cands = [process.env.PYTHON, path.join(ROOT, '.venv/bin/python'), path.join(ROOT, '.venv/Scripts/python.exe'),
    '/home/user/.venv/bin/python', 'python3', 'python'].filter(Boolean);
  for (const c of cands) {
    try {
      execFileSync(c, ['-c', 'import sys'], { stdio: 'ignore' });
      return c;
    } catch { /* next */ }
  }
  assert.fail('no Python interpreter found — set PYTHON=<path> (the probes are generated by app/browser/dom_highlight.py)');
}

let PROBES;
before(() => {
  const py = findPython();
  const json = execFileSync(py, ['-c', PY_GEN], { cwd: ROOT, encoding: 'utf-8' });
  PROBES = JSON.parse(json);
});

/* ---------- stub DOM: just what the probes touch ---------- */

class Node {
  constructor(tag, { text = '', cls = '', children = [], visible = true, disabled = false } = {}) {
    this.tagName = tag.toUpperCase();
    this.className = cls;
    this._text = text;
    this.children = children;
    this.children.forEach((c) => { c.parentNode = this; });
    this._visible = visible;
    this.disabled = disabled;
    this.isConnected = true;
    this.parentNode = null;
    this.clicks = 0;
    this.attrs = {};
    this.style = {};
  }
  get textContent() { return this._text + this.children.map((c) => c.textContent).join(''); }
  set textContent(v) { this._text = v; this.children = []; }
  get offsetWidth() { return this._visible ? 10 : 0; }
  get offsetHeight() { return this._visible ? 10 : 0; }
  getClientRects() { return this._visible ? [{}] : []; }
  getBoundingClientRect() { return { left: 5, top: 6, width: this._visible ? 10 : 0, height: this._visible ? 10 : 0 }; }
  matches(sel) { return sel === this.tagName.toLowerCase(); }
  querySelector(sel) { return this.querySelectorAll(sel)[0] || null; }
  querySelectorAll(sel) {
    const out = [];
    const walk = (n) => n.children.forEach((c) => { if (c.tagName.toLowerCase() === sel) out.push(c); walk(c); });
    walk(this);
    return out;
  }
  setAttribute(k, v) { this.attrs[k] = v; }
  appendChild(c) { c.parentNode = this; this.children.push(c); return c; }
  removeChild(c) { this.children = this.children.filter((x) => x !== c); c.parentNode = null; }
  click() { this.clicks++; }
  scrollIntoView() {}
}

function makeDocument(body) {
  const doc = {
    body,
    documentElement: body,
    createElement: (tag) => new Node(tag),
    querySelector: (sel) => doc.querySelectorAll(sel)[0] || null,
    querySelectorAll(sel) {
      if (sel.startsWith('[')) {                  // '[data-arena-highlight]' — highlight boxes
        const attr = sel.slice(1, -1);
        const out = [];
        const walk = (n) => n.children.forEach((c) => { if (c.attrs && c.attrs[attr]) out.push(c); walk(c); });
        walk(body);
        return out;
      }
      return body.querySelectorAll(sel);
    },
  };
  return doc;
}

function run(js, body, extra = {}) {
  const timers = [];
  const sandbox = {
    JSON, Math, String, Array, Object, Set,
    document: makeDocument(body),
    setTimeout: (fn) => { timers.push(fn); return timers.length; },
    ...extra,
  };
  sandbox.window = sandbox;
  sandbox.window.getComputedStyle = (el) => ({ display: el._visible ? 'block' : 'none', visibility: 'visible', pointerEvents: 'auto' });
  vm.createContext(sandbox);
  const raw = vm.runInContext(js, sandbox);
  return { res: JSON.parse(raw), sandbox, timers };
}

function page() {
  const label = new Node('span', { text: 'New\n   Chat' });
  const send = new Node('button', { text: 'Send', cls: 'btn primary', children: [new Node('svg')] });
  const hidden = new Node('button', { text: 'Hidden', visible: false });
  const newChat = new Node('button', { children: [label], cls: 'nav' });
  const body = new Node('body', { children: [hidden, send, newChat] });
  return { body, send, newChat, hidden, label };
}

/* ---------- syntax: every generated probe compiles ---------- */

describe('generated probes compile (the §B9 regression)', () => {
  test('every probe is valid JavaScript', () => {
    for (const [name, js] of Object.entries(PROBES)) {
      assert.doesNotThrow(() => new vm.Script(js, { filename: name + '.js' }), `${name} does not compile`);
    }
  });
});

/* ---------- FIND ---------- */

describe('find probe', () => {
  test('finds the first VISIBLE-or-not match, reports total/index/text/visible, stashes the node, highlights', () => {
    const p = page();
    const { res, sandbox, timers } = run(PROBES.find_plain, p.body);
    assert.equal(res.error, null);
    assert.equal(res.phase, 'find');
    assert.equal(res.total, 3);
    assert.equal(res.found, true);
    assert.equal(res.index, 0);                    // first match is the hidden button…
    assert.equal(res.visible, false);              // …and the probe says so (click phase decides)
    assert.equal(res.text, 'Hidden');
    assert.equal(sandbox.window.__arenaStash, p.hidden);
    assert.equal(res.highlighted, false);          // zero-size rect → no box
    assert.equal(res.candidates.length, 3);
    assert.deepEqual(res.candidates.map((c) => c.text), ['Hidden', 'Send', 'New Chat']);
    assert.equal(timers.length, 0);
  });

  test('label_selector + contains: whitespace-collapsed child text selects the right button', () => {
    const p = page();
    const { res, sandbox } = run(PROBES.find_label_contains, p.body);
    assert.equal(res.error, null);
    assert.equal(res.found, true);
    assert.equal(res.index, 2);
    assert.equal(res.text, 'New Chat');            // "New\n   Chat" collapsed
    assert.equal(res.visible, true);
    assert.equal(res.clickable, true);
    assert.equal(res.target_desc, 'button.nav');
    assert.equal(sandbox.window.__arenaStash, p.newChat);
  });

  test('label_selector + exact: only the exact label matches; a miss reports found=false with total', () => {
    const p = page();
    assert.equal(run(PROBES.find_label_exact, p.body).res.found, true);
    p.label.textContent = 'New Chat!';
    const miss = run(PROBES.find_label_exact, p.body).res;
    assert.equal(miss.found, false);
    assert.equal(miss.total, 3);
    assert.equal(miss.error, null);
  });

  test('match_text without label_selector matches the element text itself', () => {
    const p = page();
    const { res } = run(PROBES.find_text_exact_nolabel, p.body);
    assert.equal(res.found, true);
    assert.equal(res.index, 1);
    assert.equal(res.text, 'Send');
    assert.equal(res.target_desc, 'button.btn.primary');
  });

  test('highlight on a visible match appends ONE box with the highlight attribute and schedules its removal', () => {
    const p = page();
    p.hidden._visible = true;
    const { res, sandbox, timers } = run(PROBES.find_plain, p.body);
    assert.equal(res.highlighted, true);
    assert.deepEqual(res.rect, { x: 5, y: 6, width: 10, height: 10 });
    const boxes = sandbox.document.querySelectorAll('[data-arena-highlight]');
    assert.equal(boxes.length, 1);
    assert.equal(timers.length, 1);
    timers[0]();
    assert.equal(sandbox.document.querySelectorAll('[data-arena-highlight]').length, 0);
  });

  test('a probe exception is reported in out.error, never thrown', () => {
    const p = page();
    const doc = makeDocument(p.body);
    doc.querySelectorAll = () => { throw new Error('bad selector'); };
    const sandbox = { JSON, Math, String, Array, Object, document: doc, setTimeout() {} };
    sandbox.window = sandbox; sandbox.window.getComputedStyle = () => ({});
    vm.createContext(sandbox);
    const res = JSON.parse(vm.runInContext(PROBES.find_plain, sandbox));
    assert.equal(res.found, false);
    assert.equal(res.error, 'bad selector');
  });
});

/* ---------- CLICK (stage + dispatch) ---------- */

describe('click probe', () => {
  test('without a stash it reports the error instead of clicking anything', () => {
    const p = page();
    const { res } = run(PROBES.click_go, p.body);
    assert.equal(res.clicked, false);
    assert.match(res.error, /no element stashed/);
  });

  test('stage: reports clickability + highlights, never clicks; dispatch: clicks the stashed element once', () => {
    const p = page();
    const stage = run(PROBES.click_stage, p.body, { __arenaStash: p.send });
    assert.equal(stage.res.clickable, true);
    assert.equal(stage.res.highlighted, true);
    assert.equal(stage.res.clicked, false);
    assert.equal(p.send.clicks, 0);
    const go = run(PROBES.click_go, p.body, { __arenaStash: p.send });
    assert.equal(go.res.clicked, true);
    assert.equal(go.res.clicked_target, 'button.btn.primary');
    assert.equal(p.send.clicks, 1);
  });

  test('click_selector resolves an inner element; missing inner target is an error, not a click', () => {
    const p = page();
    const inner = run(PROBES.click_inner, p.body, { __arenaStash: p.send });
    assert.equal(inner.res.clicked, true);
    assert.equal(inner.res.clicked_target, 'svg');
    assert.equal(p.send.clicks, 0);
    assert.equal(p.send.children[0].clicks, 1);
    const miss = run(PROBES.click_inner, p.body, { __arenaStash: p.newChat });
    assert.equal(miss.res.clicked, false);
    assert.match(miss.res.error, /click target svg not found/);
  });

  test('a detached stash is refused', () => {
    const p = page();
    p.send.isConnected = false;
    const { res } = run(PROBES.click_go, p.body, { __arenaStash: p.send });
    assert.equal(res.clicked, false);
    assert.match(res.error, /no longer attached/);
  });

  test('disabled / hidden targets are not clicked', () => {
    const p = page();
    p.send.disabled = true;
    const { res } = run(PROBES.click_go, p.body, { __arenaStash: p.send });
    assert.equal(res.clickable, false);
    assert.equal(res.clicked, false);
    assert.equal(p.send.clicks, 0);
  });
});

/* ---------- HIGHLIGHT + CLEAR ---------- */

describe('highlight + clear probes', () => {
  test('highlight probe with label filter marks the matching element and clear removes the box', () => {
    const p = page();
    const { res, sandbox } = run(PROBES.highlight, p.body);
    assert.equal(res.error, null);
    assert.equal(res.found, true);
    assert.equal(res.text, 'New Chat');
    assert.equal(res.highlighted, true);
    assert.equal(sandbox.document.querySelectorAll('[data-arena-highlight]').length, 1);
    const cleared = JSON.parse(vm.runInContext(PROBES.clear, sandbox));
    assert.deepEqual(cleared, { cleared: 1 });
    assert.equal(sandbox.document.querySelectorAll('[data-arena-highlight]').length, 0);
  });
});
