/* Tier A — the Firefox macro's find-rectangle script (Node.js, no browser).

   RULE 8: the payload is generated by the REAL Python builder
   (app/browser/uivision/macro.py `render_find_rect_js` — the same
   JSON.stringify rendering the Ui.Vision extension applies to
   `${!cmd_var1..2}` inside `executeScript`) and is EXECUTED against a
   stub document. This is the visual-confirmation half of the framework
   test (2026-09-23, owner: "draw rect visual confirmation the element
   was found"): element found ⇒ one #ff2d2d rectangle over the element,
   held, then removed; absent ⇒ resolves "not found" (the XClick gate
   decides); image/OCR/x,y ⇒ resolves "skipped" (the extension draws its
   own vision box). The script must NEVER reject — the observation never
   fails the run (D-3). */

import { test, describe, before } from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import vm from 'node:vm';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');

const PY_GEN = `
import json
from app.browser.uivision import macro
out = {
  "found_css":   macro.render_find_rect_js("css=.nav", 1200),
  "found_id":    macro.render_find_rect_js("id=new-chat", 1200),
  "found_xpath": macro.render_find_rect_js("xpath=//a[span[text()='New Chat']]", 1200),
  "found_text":  macro.render_find_rect_js("text=New Chat", 1200),
  "found_dom":   macro.render_find_rect_js("dom=document.querySelector('.nav')", 1200),
  "bad_xpath":   macro.render_find_rect_js("xpath=( ( (", 1200),
  "absent_css":  macro.render_find_rect_js("css=.missing", 1200),
  "image":       macro.render_find_rect_js("button.png@@0.8", 1200),
  "coords":      macro.render_find_rect_js("10,20", 1200),
}
print(json.dumps(out))
`;

function findPython() {
  const cands = [process.env.PYTHON, path.join(ROOT, '.venv/bin/python'),
    path.join(ROOT, '.venv/Scripts/python.exe'), '/home/user/.venv/bin/python', 'python3', 'python']
    .filter(Boolean);
  for (const c of cands) {
    try { execFileSync(c, ['-c', 'import sys'], { stdio: 'ignore' }); return c; } catch { /* next */ }
  }
  assert.fail('no Python interpreter found — set PYTHON=<path>');
}

let PAYLOADS;
before(() => {
  const py = findPython();
  PAYLOADS = JSON.parse(execFileSync(py, ['-c', PY_GEN], { cwd: ROOT, encoding: 'utf-8' }));
});

/* ---------- stub DOM: just what the script touches ---------- */

class Node {
  constructor(tag, { text = '', cls = '', id = '', children = [], rect = { left: 0, top: 0, width: 10, height: 10 } } = {}) {
    this.tagName = tag.toUpperCase();
    this.className = cls;
    this._text = text;
    this.children = children;
    this.children.forEach((c) => { c.parentNode = this; });
    this.rect = rect;
    this.attrs = {};
    if (id) this.attrs.id = id;
    this.parentNode = null;
    this.scrollIntoViewCalls = 0;
  }
  get textContent() { return this._text + this.children.map((c) => c.textContent).join(''); }
  scrollIntoView() { this.scrollIntoViewCalls++; }
  getBoundingClientRect() { return this.rect; }
  setAttribute(k, v) { this.attrs[k] = v; }
  appendChild(c) { c.parentNode = this; this.children.push(c); return c; }
  removeChild(c) { this.children = this.children.filter((x) => x !== c); c.parentNode = null; }
  *walk() { for (const c of this.children) { yield c; yield* c.walk(); } }
}

function evaluateXpath(body, xp) {
  if (xp.startsWith('//*[contains(text(), ')) {
    const quoted = xp.match(/contains\(text\(\), '(.*)'\)/);
    const want = quoted ? quoted[1] : null;
    for (const n of body.walk()) if (want && n._text.includes(want)) return n;  // text() = own text
    return null;
  }
  const anchor = xp.match(/^\/\/a\[span\[text\(\)='(.*)'\]\]$/);
  if (anchor) {
    for (const n of body.walk()) {
      if (n.tagName !== 'A') continue;
      const span = n.children.find((c) => c.tagName === 'SPAN' && c._text === anchor[1]);
      if (span) return n;
    }
    return null;
  }
  throw new Error('stub evaluate: unsupported xpath ' + xp);
}

function makeDocument(body) {
  const doc = {
    body,
    documentElement: body,
    createElement: (tag) => new Node(tag),
    getElementById: (id) => { for (const n of [body, ...body.walk()]) if (n.attrs.id === id) return n; return null; },
    querySelector: (sel) => {
      if (sel.startsWith('.')) {
        const cls = sel.slice(1);
        for (const n of [body, ...body.walk()]) if (n.className === cls) return n;
        return null;
      }
      return null;
    },
    evaluate: (xp, _ctx, _res, _type, _r) => ({ singleNodeValue: evaluateXpath(body, xp) }),
  };
  return doc;
}

/* a controllable clock: setTimeout lands on a queue the test advances */
function makeClock() {
  let now = 0;
  const queue = [];
  return {
    now: () => now,
    advance(ms) {
      const target = now + ms;
      for (;;) {
        if (!queue.length) break;
        queue.sort((a, b) => a.at - b.at);
        if (queue[0].at > target) break;
        now = queue[0].at;
        queue.shift().fn();
      }
      now = target;
    },
    setTimeout: (fn, ms) => { queue.push({ at: now + (Number(ms) || 0), fn }); return queue.length; },
  };
}

function makePage() {
  const span = new Node('span', { text: 'New Chat', rect: { left: 14, top: 24, width: 92, height: 22 } });
  const nav = new Node('a', { cls: 'nav', children: [span], rect: { left: 10, top: 20, width: 100, height: 30 } });
  const btn = new Node('button', { cls: 'btn', id: 'new-chat', rect: { left: 500, top: 400, width: 80, height: 24 } });
  const body = new Node('body', { children: [nav, btn] });
  return { body, nav, span, btn };
}

const rects = (body) => body.children.filter((c) => c.tagName === 'DIV' && c.attrs.style);

function start(name, page) {
  const clock = makeClock();
  const sandbox = {
    JSON, Math, String, parseInt,
    Date: { now: clock.now },
    setTimeout: clock.setTimeout,
    XPathResult: { FIRST_ORDERED_NODE_TYPE: 9 },
    document: makeDocument(page.body),
  };
  sandbox.window = sandbox;
  vm.createContext(sandbox);
  const promise = vm.runInContext(PAYLOADS[name], sandbox, { filename: name + '.js' });
  return { promise, sandbox, clock, body: page.body, page, drawnNow: () => rects(page.body) };
}

/* advance to the budget (and past it): the pending promise settles, the
   hold timer fires and the tick loop stops */
async function finish(handle, budget = 1200) {
  handle.clock.advance(budget + 400);
  const msg = await handle.promise;
  return { msg, sandbox: handle.sandbox, body: handle.body };
}

/* ---------- syntax: every rendered payload compiles ---------- */

describe('rendered find-rect payloads compile', () => {
  test('every payload is valid JavaScript with no unrendered references', () => {
    for (const [name, js] of Object.entries(PAYLOADS)) {
      assert.doesNotThrow(() => new vm.Script(js, { filename: name + '.js' }), `${name} does not compile`);
      assert.ok(!js.includes('${'), `${name}: unrendered variable reference left in the payload`);
    }
  });
});

/* ---------- element found ⇒ RED rectangle, held, removed ---------- */

describe('element found', () => {
  test('css= draws one #ff2d2d rectangle over the element, holds it, then removes it', async () => {
    const p = makePage();
    const before = p.body.children.length;
    const h = start('found_css', p);
    const drawn = h.drawnNow();                                // the first tick ran at t=0
    assert.equal(drawn.length, 1, 'rectangle visible while the macro waits for the click');
    const style = drawn[0].attrs.style;
    assert.match(style, /border:3px solid #ff2d2d/);           // RULE 1 COLOR_FIND
    assert.match(style, /pointer-events:none/);                // never intercepts the XClick
    assert.match(style, /position:fixed/);
    assert.match(style, /left:6px; top:16px; width:108px; height:38px/);  // the element's box, padded
    assert.equal(p.nav.scrollIntoViewCalls, 1);                // brought into view for the native click
    assert.equal(p.body.children.length, before + 1);
    const { msg, body } = await finish(h);
    assert.match(msg, /element found — RED confirmation rectangle drawn/);
    assert.equal(rects(body).length, 0, 'the hold timer removed the rectangle');
  });

  test('xpath=/text=/id=/dom= all resolve through their own locator path', async () => {
    for (const name of ['found_xpath', 'found_text', 'found_id', 'found_dom']) {
      const p = makePage();
      const h = start(name, p);
      assert.equal(h.drawnNow().length, 1, name);
      const { msg, body } = await finish(h);
      assert.match(msg, /element found/, name);
      assert.equal(rects(body).length, 0, name);
    }
  });

  test('text= boxes the element carrying the text (own text nodes, not descendants)', async () => {
    const p = makePage();
    const h = start('found_text', p);
    const [rect] = h.drawnNow();
    // the span's box (14/24/92/22) padded; if the anchor had matched it would be 6/16/108/38
    assert.match(rect.attrs.style, /left:10px; top:20px; width:100px; height:30px/);
    await finish(h);
  });

  test('a malformed xpath never rejects — it answers like an absent element', async () => {
    const p = makePage();
    const h = start('bad_xpath', p);
    assert.equal(h.drawnNow().length, 0);
    const { msg, body } = await finish(h);
    assert.match(msg, /element not found within 1200 ms/);
    assert.equal(rects(body).length, 0);
  });
});

/* ---------- absent / non-locator targets: honest answers, never a throw ---------- */

describe('absent and non-locator targets', () => {
  test('an absent element resolves "not found — the XClick gate decides" (the click stays the strict gate)', async () => {
    const p = makePage();
    const h = start('absent_css', p);
    assert.equal(h.drawnNow().length, 0);
    const { msg, body } = await finish(h);
    assert.match(msg, /element not found within 1200 ms — the XClick gate decides/);
    assert.equal(rects(body).length, 0);
  });

  test('image and x,y targets resolve "skipped" at once — the extension draws its own vision box', async () => {
    for (const name of ['image', 'coords']) {
      const p = makePage();
      const h = start(name, p);
      assert.equal(h.drawnNow().length, 0);
      const { msg, body } = await finish(h);
      assert.match(msg, /skipped: not an element locator/);
      assert.equal(rects(body).length, 0);
    }
  });
});
