"""AREA B — the public surface of `stores/` is frozen; only additions allowed.

Design ref: docs/archive/2026-09-09-four-area-refactor/REFACTOR_2026-09-09_AREA_B_DESIGN.md §3 and §6.1;
plan §7.3 rule 1 ("No area renames, moves, or changes the signature of any
symbol that another area imports").

`api_baseline.json` (generated by `tools/metrics/stores_api.py --write`) records
every public module-level symbol of `stores/`, every public method of every
class, and their `inspect.signature` text plus parameter names. This test
rebuilds that surface from the live package and fails on

  * a removed symbol,
  * a removed method,
  * a signature change that is not on the documented allowlist,
  * an allowlisted signature that renamed or dropped a parameter (a widening
    must keep every old parameter, otherwise the callers B1 promises not to
    touch would break),
  * any change at all inside the three frozen modules.

Run with:  python3 tests/unit/stores/test_stores_public_api.py
      or:  python tools/metrics/stores_api.py --write   (after a deliberate change)
"""

import importlib
import importlib.util
import json
import os
import sys
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))))
sys.path.insert(0, ROOT)

HERE = os.path.dirname(os.path.abspath(__file__))
BASELINE = os.path.join(HERE, "api_baseline.json")

_spec = importlib.util.spec_from_file_location(
    "stores_api", os.path.join(ROOT, "tools", "metrics", "stores_api.py"))
stores_api = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(stores_api)

#: the names B1 widens ON PURPOSE (docs/archive/2026-09-09-four-area-refactor/REFACTOR_2026-09-09_AREA_B_DESIGN.md
#: §6.1). Every entry must keep all of its old parameters — a widening, never
#: a rename. Anything not on this list that differs fails the test.
WIDENED = frozenset({
    # ── P1-3: one constructor for every config store ─────────────────
    # `Store(atomic | path, *, data=None)`; the payload slot of the old
    # signature keeps its name (`path`, `data`, `save_now`, `config`), so
    # every call form that worked before still works.
    "stores.atomic.AtomicJsonStore.__init__",       # path | another atomic
    "stores.session_store.SessionStore.__init__",
    "stores.session_store.SessionStore.set",        # `save` joins `save_now`
    "stores.settings_store.SettingsStore.__init__",
    "stores.settings_store.SettingsStore.set",       # `save` joins `save_now`
    "stores.labels_file_store.LabelsFileStore.__init__",
    "stores.undo_store.UndoStore.__init__",
    "stores.block_store.BlockStore.__init__",
    "stores.bookmark_store.BookmarkStore.__init__",
    "stores.preset_store.PresetStore.__init__",      # config | atomic | path
    # ── one lifecycle: `save(force=False)` / `flush()` answer `bool`, and
    #    every store can be told to persist (ConfigManager.save() names all
    #    seven, and two of them used to have no `save()` at all) ──────────
    "stores.undo_store.UndoStore.save",
    "stores.undo_store.UndoStore.flush",
    "stores.block_store.BlockStore.save",
    "stores.block_store.BlockStore.flush",
    "stores.bookmark_store.BookmarkStore.save",
    "stores.bookmark_store.BookmarkStore.flush",
    "stores.labels_file_store.LabelsFileStore.data",
    # ── annotations loosened to "accept what the caller has": a path object,
    #    an AtomicJsonStore, any mapping. Parameters are unchanged. ───────
    "stores.labels_file_store.LabelsFileStore.set_data",
    "stores.block_store.BlockStore.set_all",
    "stores.block_store.BlockStore.save_custom_block",
    "stores.bookmark_store.BookmarkStore.set_all",
    # ── stores/add/removes report whether anything changed (both
    #    `test_stores_split.py` and `bridge/cdp_bridge.py` read that
    #    truthiness; the value is still a Result) ─────────────────────
    "stores.bookmark_store.BookmarkStore.add",
    "stores.bookmark_store.BookmarkStore.remove",
})

# G7 §2 (2026-09-13): the stores wide-parameter adjudication MIGRATED these
# names to parameter objects / value classes under the owner ruling that
# lifted the AREA-B freeze ("remove any restriction to all frozen solutions,
# redesign any code as needed"). Each dropped parameter set is documented in
# G7_BACKLOG_DESIGN_2026-09-13.md §2 (the conservation table: every field
# kept, every default kept, behaviour pinned by the existing suites). The
# refreshed api_baseline.json (same step) is the new post-migration surface.
MIGRATED = frozenset({
    "stores.history_models.fingerprint",           # 6 -> 2 (LineIdentity)
    "stores.history_models.dedupe_key",            # 5 -> 1 (LineIdentity)
    "stores.history_repo.HistoryRepo.append",      # 13 -> 1 (AppendRequest)
    "stores.history_repo.HistoryRepo.rename_if_same_conversation",
    #                                                 8 -> 4 (PaneSignature)
    "stores.history_repo.HistoryRepo.recover_media",  # 6 -> 1 (request)
    "stores.media_store.MediaStore.__init__",      # 6 -> 3 (MediaOptions)
})

#: `tests/unit/stores/api_baseline_pre_b1.json` is the surface as AREA B
#: found it; `api_baseline.json` is the surface after B1, which B2 may only
#: add to.
BASELINE_PRE_B1 = os.path.join(HERE, "api_baseline_pre_b1.json")

#: modules no area may touch at all (plan §7.3 rule 2)
FROZEN = ("stores.history_models", "stores.jsonio", "stores.migration")

#: every name another area imports from `stores/` — the reason the split must
#: stay internal (design §3)
REQUIRED = {
    "stores.atomic": ["AtomicJsonStore"],
    "stores.block_store": ["BlockStore"],
    "stores.bookmark_store": ["BookmarkStore", "DEFAULT_BOOKMARKS",
                              "DEFAULT_URLS"],
    "stores.session_store": ["SessionStore", "SESSION_DEFAULTS"],
    "stores.settings_store": ["SettingsStore", "SETTINGS_DEFAULTS"],
    "stores.labels_file_store": ["LabelsFileStore", "LABELS_DEFAULT"],
    "stores.undo_store": ["UndoStore", "MAX_STACK_HISTORY"],
    "stores.preset_store": ["PresetStore"],
    "stores.migration": ["migrate_legacy_config"],
    "stores.jsonio": ["load_json", "save_json", "config_dir_for"],
    "stores.history_models": ["MessageRecord", "AppendResult", "Alignment",
                              "MAX_LIVE_ITEMS", "dedupe_key", "fingerprint"],
    "stores.history_db": ["HistoryDB", "SCHEMA_VERSION", "TABLE_COLUMNS",
                          "_version_tuple", "HistoryDB._repair_tables",
                          "HistoryDB._table_columns", "HistoryDB.LATE_COLUMNS",
                          "HistoryDB._add_missing_columns",
                          "HistoryDB.db_fetch_legacy",
                          "HistoryDB._rebuild_legacy_messages",
                          "HistoryDB._migrate_dup_keys",
                          "HistoryDB.normalise_nick", "HistoryDB.file_size"],
    "stores.history_repo": ["HistoryRepo", "align_batch", "resolve_days",
                            "HistoryRepo._last_ord"],
    "stores.media_store": ["MediaStore", "slugify_nick", "MediaStore._fetch_one",
                            "MediaStore._free_name",
                            "MediaStore.folder_for", "MediaStore.NICK_MARKER"],
    "stores.label_store": ["LabelStore", "PALETTE", "DEFAULT_COLOR",
                            "MAX_NAME", "normalize_color", "FILTER_KEY"],
    "stores.user_memory": ["UserMemory", "UserRecord", "_SCHEMA"],
}


def _get(target: str):
    """Resolve `pkg.module.Class.member` against the live package."""
    obj = importlib.import_module(target)
    return obj


class ApiSurfaceCase(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cwd = os.getcwd()
        os.chdir(ROOT)
        try:
            cls.current = stores_api.surface()
        finally:
            os.chdir(cwd)
        cls.baseline = cls._load(BASELINE)
        cls.pre_b1 = cls._load(BASELINE_PRE_B1)

    @staticmethod
    def _load(path):
        with open(path, encoding="utf-8") as handle:
            return json.load(handle)


class TestSurfaceIsFrozen(ApiSurfaceCase):
    def test_the_baseline_is_not_empty(self):
        self.assertGreaterEqual(len(self.baseline), 16)
        self.assertIn("stores.history_repo", self.baseline)

    def test_b1_only_widened_the_surface_it_promised(self):
        """Against the surface as AREA B found it (`api_baseline_pre_b1`).

        This is the real "no other area had to change" proof: every store
        keeps its name, every parameter it used to accept is still accepted,
        and the only differences are the `WIDENED` ones B1 set out to make.
        """
        self.assertEqual(
            stores_api.diff(self.pre_b1, self.current, WIDENED,
                            allow_new_modules=True, migrated=MIGRATED), [],
            "the pre-B1 surface moved in a way the design doc does not "
            "account for")

    def test_nothing_was_removed_or_re_signedatured(self):
        problems = stores_api.diff(self.baseline, self.current, WIDENED,
                                   allow_new_modules=True)
        self.assertEqual(problems, [], "\n".join(problems))

    def test_the_three_frozen_modules_did_not_move_at_all(self):
        frozen_baseline = {k: v for k, v in self.baseline.items()
                           if k in FROZEN}
        frozen_current = {k: v for k, v in self.current.items()
                          if k in FROZEN}
        self.assertEqual(
            stores_api.diff(frozen_baseline, frozen_current,
                            allow_new_modules=True), [],
            "stores/history_models.py, jsonio.py and migration.py must not "
            "move without a deliberate, in-step baseline refresh (the AREA-B "
            "freeze was lifted by owner ruling 2026-09-13; history_models "
            "moved in G7 §2 — see MIGRATED — and the baseline was refreshed "
            "in that same step)")

    def test_every_allowlisted_name_keeps_its_old_parameters(self):
        for dotted in sorted(WIDENED):
            parts = dotted.split(".")
            self.assertEqual(parts[0], "stores", f"{dotted} is not in stores/")
            module = f"stores.{parts[1]}"
            rest = ".".join(parts[2:])
            expected = self._lookup(self.baseline, module, rest)
            got = self._lookup(self.current, module, rest)
            with self.subTest(name=dotted):
                self.assertIsNotNone(expected, f"{dotted} is not in the "
                                                "baseline — drop it from "
                                                "WIDENED")
                self.assertIsNotNone(got, f"{dotted} was REMOVED")
                if "params" in expected:
                    self.assertTrue(set(expected["params"])
                                    <= set(got.get("params") or ()),
                                    f"{dotted} dropped or renamed a parameter: "
                                    f"{expected['params']} -> "
                                    f"{got.get('params')}")

    @staticmethod
    def _lookup(tree, module, rest):
        entry = tree.get(module)
        if entry is None:
            return None
        if "." not in rest:
            if rest in entry["functions"]:
                return entry["functions"][rest]
            if rest in entry["constants"]:
                return {"kind": "constant"}
            if rest in entry["classes"]:
                return {"kind": "class"}
            return None
        klass, method = rest.split(".", 1)
        return entry["classes"].get(klass, {}).get(method)


class TestOtherAreasKeepImporting(ApiSurfaceCase):
    def test_every_imported_name_still_exists(self):
        for module, names in REQUIRED.items():
            mod = _get(module)
            for name in names:
                with self.subTest(name=f"{module}.{name}"):
                    target = mod
                    for part in name.split("."):
                        target = getattr(target, part)
                        self.assertIsNotNone(target)

    def test_stores_imports_outside_the_package_are_untouched(self):
        # plan §6.2 exit criterion 3: no other area had to edit an import
        count = 0
        for pkg in ("services", "backend", "actions", "bridge", "app"):
            for base, dirs, files in os.walk(os.path.join(ROOT, pkg)):
                dirs[:] = [d for d in dirs if d != "__pycache__"]
                for name in files:
                    if not name.endswith(".py"):
                        continue
                    with open(os.path.join(base, name), encoding="utf-8") as fh:
                        count += sum(1 for line in fh
                                     if line.lstrip().startswith("from stores")
                                     or " from stores." in line
                                     or "from stores import" in line)
        # The count was 33 on the pre-refactor base AREA B was authored
        # against. A's run-engine fix (+1, stores.user_memory now imported at
        # runtime in services/run/progress.py) and D's chat_sync extraction
        # (+3: SyncResult/MAX_LIVE_ITEMS/align_batch/MessageRecord) added
        # legitimate imports *before* B was merged; the B merge itself adds
        # zero. The invariant this pins is "the stores refactor must not
        # force another area to edit an import" — bump this number only when
        # another area legitimately grows the surface.
        #
        # 37 -> 38 (2026-09-11, CC-tail round E, Phase 0): the portable
        # window-preset feature grew the surface by one legitimate re-export —
        # the `backend/preset_store.py` compatibility shim's
        # `from stores.preset_store import PresetStore`. RULE 16 §16.0 waives
        # compatibility facades, so this is the sanctioned "another area
        # legitimately grows the surface" case, recorded here rather than
        # silently.
        # 38 -> 40 (2026-09-11, DB-undo-restore port): the new leaf module
        # stores/world_lock.py is imported by services/undo_archive.py (the
        # archive command retries a locked world) and by
        # services/history/mutate.py (the timeline save does the same). Both
        # are the sanctioned case again — a new leaf store, imported by the
        # two services that must survive a locked world file.
        # 40 -> 42 (2026-09-13, Round G2 RULE 18 split): the backend
        # chat_sync monolith became a seam + family; the *same* stores names
        # now sit in the files that use them — seam (SyncResult, the pinned
        # run_sync annotation), chat_sync_persist (MAX_LIVE_ITEMS,
        # SyncResult), chat_sync_read (align_batch), chat_sync_session
        # (SyncResult) — two more import lines than the monolith's two. The
        # scroll_parser family is net-zero (UserRecord moved facade ->
        # scroll_parser_dom). The stores/ surface itself is unchanged; the
        # invariant (a stores refactor never forces another area to edit an
        # import) still holds.
        # 42 -> 41 (2026-09-13, Round G4 parameter objects): the old
        # `Collector.__init__` carried `repo: HistoryRepo` as an annotation,
        # which is why services/collector_service.py imported the name. W6
        # moved the seven collaborators into the `CollectorDeps` bundle, whose
        # fields are uniformly `Any` (like every other Deps bundle — no import
        # cycles, no astroid setattr fallout), so the annotation-only import
        # went away with the signature. The stores/ surface is untouched; this
        # is a services-side refactor legitimately shrinking the count.
        # 41 -> 44 (2026-09-13, Round G7 §2 stores parameter objects): the
        # migrated facades take request objects, so three production files now
        # import the request names: services/collector_push.py (+1,
        # AppendRequest), backend/chat_sync_persist.py (+1, one
        # stores.history_requests line shared by AppendRequest and
        # MediaRecoveryRequest), services/collector_tick.py (+1,
        # PaneSignature). services/history/__init__.py reuses its existing
        # stores.media_store import line for MediaOptions (+0). No area had
        # to edit an import to keep WORKING — these are the deliberate new
        # call shapes, ledgered here.
        # 44 -> 46 (2026-09-14, Round H Area B + Area C): Area B splits
        # history_bridge (no stores import) and cdp_client (no stores import),
        # but Area C H-C1 splits run queue (queue_order, single_target,
        # progress each carry the UserRecord guard) and collector_archive
        # now imports PaneSignature for cursor check. Both are legitimate
        # new call shapes from the run/collector family, not a stores
        # refactor forcing another area to edit an import. Baseline moves
        # 44->46, ledgered here.
        self.assertEqual(count, 46,
                         "stores/ must be refactored without touching a single "
                         "import in another area (integrated baseline: 46)")


if __name__ == "__main__":
    unittest.main()
